[package]
name = "humanode-peer"
version = "0.1.0"
edition = "2018"
authors = ["Humanode Team <core@humanode.io>"]
publish = false

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
